services:
  - type: web
    name: image-search-api
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    rootDir:py
    envVars:
      - key: FLASK_ENV
        value: production
